//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 10:54:52 AM CDT 
//


package com.mrc.xmlfile.appspecs;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mrc.xmlfile.appspecs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mrc.xmlfile.appspecs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link Application.Properties }
     * 
     */
    public Application.Properties createApplicationProperties() {
        return new Application.Properties();
    }

    /**
     * Create an instance of {@link Application.Links }
     * 
     */
    public Application.Links createApplicationLinks() {
        return new Application.Links();
    }

    /**
     * Create an instance of {@link Application.Extobjects }
     * 
     */
    public Application.Extobjects createApplicationExtobjects() {
        return new Application.Extobjects();
    }

    /**
     * Create an instance of {@link Application.Extobjects.Extobject }
     * 
     */
    public Application.Extobjects.Extobject createApplicationExtobjectsExtobject() {
        return new Application.Extobjects.Extobject();
    }

    /**
     * Create an instance of {@link Application.Extobjects.Extobject.Parameters }
     * 
     */
    public Application.Extobjects.Extobject.Parameters createApplicationExtobjectsExtobjectParameters() {
        return new Application.Extobjects.Extobject.Parameters();
    }

    /**
     * Create an instance of {@link Application.Calculations }
     * 
     */
    public Application.Calculations createApplicationCalculations() {
        return new Application.Calculations();
    }

    /**
     * Create an instance of {@link Application.Selections }
     * 
     */
    public Application.Selections createApplicationSelections() {
        return new Application.Selections();
    }

    /**
     * Create an instance of {@link Application.Keys }
     * 
     */
    public Application.Keys createApplicationKeys() {
        return new Application.Keys();
    }

    /**
     * Create an instance of {@link Application.Fields }
     * 
     */
    public Application.Fields createApplicationFields() {
        return new Application.Fields();
    }

    /**
     * Create an instance of {@link Application.Properties.Property }
     * 
     */
    public Application.Properties.Property createApplicationPropertiesProperty() {
        return new Application.Properties.Property();
    }

    /**
     * Create an instance of {@link Application.Links.Link }
     * 
     */
    public Application.Links.Link createApplicationLinksLink() {
        return new Application.Links.Link();
    }

    /**
     * Create an instance of {@link Application.Extobjects.Extobject.Parameters.Parameter }
     * 
     */
    public Application.Extobjects.Extobject.Parameters.Parameter createApplicationExtobjectsExtobjectParametersParameter() {
        return new Application.Extobjects.Extobject.Parameters.Parameter();
    }

    /**
     * Create an instance of {@link Application.Calculations.Calculation }
     * 
     */
    public Application.Calculations.Calculation createApplicationCalculationsCalculation() {
        return new Application.Calculations.Calculation();
    }

    /**
     * Create an instance of {@link Application.Selections.Selection }
     * 
     */
    public Application.Selections.Selection createApplicationSelectionsSelection() {
        return new Application.Selections.Selection();
    }

    /**
     * Create an instance of {@link Application.Keys.Key }
     * 
     */
    public Application.Keys.Key createApplicationKeysKey() {
        return new Application.Keys.Key();
    }

    /**
     * Create an instance of {@link Application.Fields.Field }
     * 
     */
    public Application.Fields.Field createApplicationFieldsField() {
        return new Application.Fields.Field();
    }

}
